# Generated by Django 4.0.4 on 2022-05-26 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0008_alter_profile_birthday'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birthday', models.DateField(blank=True, default='2000-12-31', max_length=200, null=True)),
                ('age', models.PositiveIntegerField(blank=True, default='20', null=True)),
                ('skill_1', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('skill_2', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('bio', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('description', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('website', models.CharField(blank=True, default='', max_length=200, null=True)),
                ('degree', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('phone', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('city', models.CharField(blank=True, default='', max_length=100, null=True)),
                ('freelance', models.CharField(default='Unavailable', max_length=20)),
                ('about_image', models.ImageField(blank=True, null=True, upload_to='about_images')),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='about_image',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='bio',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='birthday',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='degree',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='freelance',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_1',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='skill_2',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='website',
        ),
    ]
