# Generated by Django 4.0.4 on 2022-05-29 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('theblog', '0012_remove_about_user_about_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='profile',
        ),
        migrations.AddField(
            model_name='about',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
