# Generated by Django 4.0.4 on 2022-05-31 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0013_remove_about_profile_about_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='verified',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
