# Generated by Django 4.0.4 on 2022-06-01 04:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0015_profile_email_profile_first_name_profile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
    ]
