# Generated by Django 4.0.4 on 2022-06-01 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0016_remove_profile_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='first_name',
            field=models.CharField(blank=True, default='<django.db.models.query_utils.DeferredAttribute object at 0x000000E2A5868940>', max_length=255, null=True),
        ),
    ]
