# Generated by Django 4.0.4 on 2022-06-01 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0019_profile_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
    ]
