# Generated by Django 4.0.4 on 2022-06-18 23:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('theblog', '0021_alter_profile_verified'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='theblog.profile')),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='friend',
            field=models.ManyToManyField(related_name='friend', to='theblog.friend'),
        ),
    ]
